dubbo:
  application:
    name: mis-system-web
    qos-port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:192.168.17.129}:2181
  consumer:
    timeout: 10000
  provider:
    timeout: 30000